name: rl-wireless
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - scipy>=1.10.1
  - numba>=0.51.2
  - torch>=2.0.0
  - torchaudio>=2.0.1
  - torchvision>=0.15.1
  - pip:
      - ray[default,air,tune,rllib,serve]==2.20.0
      - gymnasium==0.28.1
      - torch-tb-profiler>=0.4.1
      - tensorboard
